version: "3"

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"

services:
  ### PHP-FPM ##############################################
  workspace:
    build:
      context: ./workspace
    volumes:
      - ..:/var/www:cached

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ..:/var/www:cached
    expose:
      - "9000"

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
    volumes:
      - ..:/var/www:cached
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  ### MySQL ################################################
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/.laradock/data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"

  ### Redis ################################################
  redis:
    build: ./redis
    volumes:
      - ~/.laradock/data/redis:/data
    ports:
      - "6379:6379"

